"""init

Revision ID: 20318da1d804
Revises: 
Create Date: 2025-11-15 17:32:28.372431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20318da1d804'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_movies_average_rating'), table_name='movies')
    op.create_index('idx_movies_average_rating', 'movies', [sa.literal_column('average_rating DESC')], unique=False)
    op.drop_index(op.f('idx_movies_release_date'), table_name='movies')
    op.create_index('idx_movies_release_date', 'movies', [sa.literal_column('release_date DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_movies_release_date', table_name='movies')
    op.create_index(op.f('idx_movies_release_date'), 'movies', ['release_date'], unique=False)
    op.drop_index('idx_movies_average_rating', table_name='movies')
    op.create_index(op.f('idx_movies_average_rating'), 'movies', ['average_rating'], unique=False)
    # ### end Alembic commands ###
