"""add index

Revision ID: 7dcf67c81f71
Revises: 9343e872b094
Create Date: 2025-11-14 20:53:46.335903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dcf67c81f71'
down_revision: Union[str, Sequence[str], None] = '9343e872b094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_movies_average_rating', 'movies', [sa.literal_column('average_rating DESC')], unique=False)
    op.create_index('idx_movies_release_date', 'movies', [sa.literal_column('release_date DESC')], unique=False)
    op.create_index(op.f('ix_movies_genres_genre_id'), 'movies_genres', ['genre_id'], unique=False)
    op.create_index(op.f('ix_movies_genres_movie_id'), 'movies_genres', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_genres_movie_id'), table_name='movies_genres')
    op.drop_index(op.f('ix_movies_genres_genre_id'), table_name='movies_genres')
    op.drop_index('idx_movies_release_date', table_name='movies')
    op.drop_index('idx_movies_average_rating', table_name='movies')
    # ### end Alembic commands ###
