"""Add test

Revision ID: 8215ca06cfd8
Revises: 
Create Date: 2025-11-12 19:21:35.259122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8215ca06cfd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('test_string', sa.String(length=100), nullable=True))
    op.add_column('movies', sa.Column('test_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'test_date')
    op.drop_column('movies', 'test_string')
    # ### end Alembic commands ###
