"""init

Revision ID: 83d04e650421
Revises: 
Create Date: 2025-11-15 17:19:26.285954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '83d04e650421'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_table('people',
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_index(op.f('ix_people_name'), 'people', ['name'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role_enum'), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('movies_genres',
    sa.Column('movie_id', sa.String(length=36), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_index(op.f('ix_movies_genres_genre_id'), 'movies_genres', ['genre_id'], unique=False)
    op.create_index(op.f('ix_movies_genres_movie_id'), 'movies_genres', ['movie_id'], unique=False)
    op.create_table('movies_people',
    sa.Column('crew_id', sa.String(length=36), nullable=False),
    sa.Column('movie_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('Director', 'Actor', 'Writer', 'Producer', name='crew_role_enum'), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.person_id'], ),
    sa.PrimaryKeyConstraint('crew_id')
    )
    op.create_index(op.f('ix_movies_people_movie_id'), 'movies_people', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movies_people_person_id'), 'movies_people', ['person_id'], unique=False)
    op.create_table('reviews',
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('movie_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 10', name='ck_rating_range'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.movie_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_user_movie_review')
    )
    op.create_index(op.f('ix_reviews_movie_id'), 'reviews', ['movie_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.add_column('movies', sa.Column('synopsis', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('runtime_minutes', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('language', sa.String(length=50), nullable=True))
    op.add_column('movies', sa.Column('poster_url', sa.String(length=1024), nullable=True))
    op.add_column('movies', sa.Column('average_rating', sa.Numeric(precision=4, scale=2), server_default='0.00', nullable=False))
    op.add_column('movies', sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('movies', 'country',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index('idx_movies_average_rating', 'movies', [sa.literal_column('average_rating DESC')], unique=False)
    op.create_index('idx_movies_release_date', 'movies', [sa.literal_column('release_date DESC')], unique=False)
    op.drop_column('movies', 'test_string')
    op.drop_column('movies', 'test_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('test_date', sa.DATE(), nullable=True))
    op.add_column('movies', sa.Column('test_string', mysql.VARCHAR(length=100), nullable=True))
    op.drop_index('idx_movies_release_date', table_name='movies')
    op.drop_index('idx_movies_average_rating', table_name='movies')
    op.alter_column('movies', 'country',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('movies', 'rating_count')
    op.drop_column('movies', 'average_rating')
    op.drop_column('movies', 'poster_url')
    op.drop_column('movies', 'language')
    op.drop_column('movies', 'runtime_minutes')
    op.drop_column('movies', 'synopsis')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_movie_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_movies_people_person_id'), table_name='movies_people')
    op.drop_index(op.f('ix_movies_people_movie_id'), table_name='movies_people')
    op.drop_table('movies_people')
    op.drop_index(op.f('ix_movies_genres_movie_id'), table_name='movies_genres')
    op.drop_index(op.f('ix_movies_genres_genre_id'), table_name='movies_genres')
    op.drop_table('movies_genres')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_people_name'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
